import Link from "next/link";
import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Frontend Projects",
  description: "Generated by create next app | Frontend Projects",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body>
        <nav>
          <ul className="menubar">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/Contact">Contact</Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer>
          <p>Made with NextJs</p>
        </footer>
      </body>
    </html>
  );
}
